// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button']
    ATextarea: typeof import('@arco-design/web-vue')['Textarea']
    MainView: typeof import('./src/components/MainView.vue')['default']
  }
}

export {}
